# Additional options for clddctd-metrics-exporter
# Leave empty to use built-in defaults.
# Example:
# EXPORTER_OPTS="-listen :9100 -lease-file /var/lib/misc/dnsmasq.leases -ping-cycle-duration 5s"
EXPORTER_OPTS=""
